# -*- coding: utf-8 -*-
"""TN election

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NN4tVl2zjRWPTq9A4pHUaHidruS1VHJA
"""

import pandas as pd
import io
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]  # Get the name of the uploaded file
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("First 5 rows of the dataset:")
print(df.head())

df.columns = df.columns.str.strip().str.replace('-', '')

print("\nCleaned column names:")
print(df.columns)

df['Seat Efficiency'] = (pd.to_numeric(df['No. of Seats won'], errors='coerce') / pd.to_numeric(df['Total No. of Votes Polled'], errors='coerce')) * 100

df_sorted_by_seats = df.sort_values(by='No. of Seats won', ascending=False)
df_sorted_by_efficiency = df.sort_values(by='Seat Efficiency', ascending=False)

print("\nTop 5 parties by seats won:")
print(df_sorted_by_seats.head())

print("\nTop 5 parties by seat efficiency:")
print(df_sorted_by_efficiency.head())

print(df[['No. of Seats won', 'Total No. of Seats Contested']].info())

print("\nDataset with Seat Efficiency and Seat Share Percentage:")
print(df.head())

df['Seat Efficiency'] = (pd.to_numeric(df['No. of Seats won'], errors='coerce') / pd.to_numeric(df['Total No. of Votes Polled'], errors='coerce')) * 100

df['Seat Share Percentage'] = (pd.to_numeric(df['No. of Seats won'], errors='coerce') / pd.to_numeric(df['Total No. of Seats Contested'], errors='coerce')) * 100


df_sorted_by_seats = df.sort_values(by='No. of Seats won', ascending=False)
df_sorted_by_efficiency = df.sort_values(by='Seat Efficiency', ascending=False)

print("\nTop 5 parties by seats won:")
print(df_sorted_by_seats.head())

print("\nTop 5 parties by seat efficiency:")
print(df_sorted_by_efficiency.head())

top_5_vote_share = df.nlargest(5, 'Percentage of Total Votes Polled in the State')

top_5_seat_share = df.nlargest(5, 'Seat Share Percentage')

print("\nTop 5 parties by vote share:")
print(top_5_vote_share)

print("\nTop 5 parties by seat share:")
print(top_5_seat_share)

import plotly.express as px

print("\nVisualization 1: Party Performance (Seats Won vs Votes Polled)")

df['Seat Efficiency'] = df['Seat Efficiency'].fillna(0)

fig1 = px.scatter(df, x='Total No. of Votes Polled', y='No. of Seats won',
                  color='Name of the Political Party', size='Seat Efficiency',
                  title='Party Performance: Seats Won vs Votes Polled',
                  labels={'Total No. of Votes Polled': 'Votes Polled', 'No. of Seats won': 'Seats Won'})
fig1.show()

df.to_csv('analyzed_election_results.csv', index=False)
print("\nAnalyzed dataset saved as 'analyzed_election_results.csv'.")